name: Public-Server
version: ${project.version}
main: de.monaco07.publicserver.Main
api-version: 1.19
authors: [ Paul, Leonard ]
description: Öffentlicher server

commands:
  timer:
    permission: server.command.timer
  worlds:
    permission: server.command.worlds
  l:
    permission: server.command.l
  lobby:
    permission: server.command.l
  h:
    permission: server.command.l
  hub:
    permission: server.command.l